@startuml MB01101_BASELINE_V38_19
!include http://utilities.junotsystems.com:5120/plantuml/jwh-salt-chart-legend.iuml

title MB01-101 Goods Receipt for Purchase Order\nBaseline

!procedure _initial()
{
    = Initial Screen
    ---
    {
        [ MENU ]|[ RESET ]|[ POST ]
    }
    [$conditional STATUS MESSAGE]
    ...
    "$editable Purchase Order Number"
    ===
    <i>Notes
}
!endprocedure

!procedure _poNumValid()
{
    = PO Found in SAP
    ---
    {
        [ MENU ]|[ RESET ]|[ POST ]
    }
    [$conditional STATUS MESSAGE]
    ...
    "$disabled PO Number"
    ...
    $sysnote Header Fields
    "$editable Delivery Note"
    "$editable Header Text"
    ...
    $sysnote Selection Fields
    "$editable Material"
    ^$editable PO Line^
    {S
        {#
            List of Receivable PO Lines and Split Entries|*|*|*|*|*|*|*|*
            Line Num|Material|Qty to Receive|UoM|Plant|Storage Location|Batch|PO Qty|Open Qty
        }
    }
    ===
    <i>Notes
}
!endprocedure

!procedure _poLineDetail()
{
    = PO Line Selected for Receipt
    ---
    {
        [ MENU ]|[ RESET ]|[ POST ]
    }
    [$conditional STATUS MESSAGE]
    ...
    {S-
        {#
            List of Entries for Selected Material|*|*
            with|same|details
        }
    }
    Material Description
    ...
    "$editable Quantity to Receive"
    ...
    $sysnote Material Destination Fields
    ^$editable Storage Location^
    "$editable $conditional Batch"
    ...
    $sysnote Serial Number Fields
    {S
        {#
            $conditional List of Entered Serial Numbers
            Serial Number
        }
    }
    "$editable $conditional Serial Number"
    ...
    {
        [ ADD ]|[ LIST ]|[ BACK ]|[ CLEAR ]|[ NEXT ]|[ SAVE ]
    }
    ===
    <i>Notes
    Default Quantity to 0
    Only show Batch field if Material is batch-managed
    Only show Serial Number fields if Material has serial number profile
    . and saved receipt quantity > 0
    If Storage Location and/or Batch value is specified in document,
    . those value(s) default and cannot be changed, but a new entry for the same
    . material with different value(s) can be added (e.g., batch split)
}
!endprocedure

!procedure _saving()
{
    = Updating Receipts
    ===
    <i>Notes
    Unposted receipt details gathered so far stored in internal workset
    Multiple lines may be gathered for posting to a single GR Document
}
!endprocedure

!procedure _posted()
{
    = Post Sent to SAP
    ===
    <i>Notes
    Only send entries with unposted receipt quantites > 0
}
!endprocedure

(*) --> [$button Menu Selection] SALT(initial)
initial --> [$userentry PO Number Entry\n(If PO found in SAP)] "Gathering Data" as Gathering<<ScreenGroup>>
Gathering --> [$button POST] SALT(posted)
posted -$sysevt-> [$sysentry Failed Post to SAP] Gathering
Gathering --> [$button RESET\n(If all entries have qty = 0)\nDiscard all entries\nClear header fields] initial
posted -$sysevt-> [$sysentry Successful Post to SAP\nShow Document Number in status message] initial

partition "Gathering Data" {
    Gathering -[dotted]-> SALT(poNumValid)
    poNumValid --> [$userentry Material Entry\n(If material is valid)\nor\n$userentry Item Selection] SALT(poLineDetail)
    poLineDetail --> [$button LIST] poNumValid
    poLineDetail --> [$button BACK or NEXT\nMove to previous or next entry] poLineDetail
    poNumValid --> [$button RESET\n(If any entries have qty > 0)\nDiscard any split entries\nReread lines from Purchase Order] poNumValid
    poLineDetail --> [$userentry Serial Number Entry\nAdd new entry to list of serial numbers\nor remove duplicate entry from list] poLineDetail
    poLineDetail --> [$button ADD\n(If current entry is complete\nand destination values differ from existing entries)] SALT(saving)
    poLineDetail --> [$button SAVE\n(If current entry is complete\nand destination values do not conflict with document\nor existing entries)] saving
    poLineDetail --> [$button CLEAR\nFor current entry only\nIf quantity > 0, reset all values\nIf quantity = 0, remove entry from screen] saving
    saving -$sysevt-> [$sysentry Stay on same item\n(If entries exist)] poLineDetail
    saving -$sysevt-> [$sysentry Return to listing\n(If no entries remain for current item)] poNumValid
}

@enduml

