@startuml MI0405_BASELINE_V39
!include http://utilities.junotsystems.com:5120/plantuml/jwh-salt-chart-legend.iuml

title MI04/MI05 Inventory Count\nBASELINE v39

!procedure _initial()
{
    = Initial Screen
    ---
    {
        [ MENU ]|[ CLEAR ]|[ POST ]
    }
    ...
    "$editable Plant"
    "$editable Storage Location"
    "$editable Material"
    "$editable Count"
    ^$editable Unit of Measure^
    [ COUNT ]
    Cumulative Count
    Inventory Document
    System Quantity
    Posted Quantity
    ===
    <i>Notes
}
!endprocedure

!procedure _materialValid()
{
    = Material Found on Open Inventory Document in SAP
    ---
    {
        [ MENU ]|[ CLEAR ]|[ POST ]
    }
    ...
    [ $conditional PREV COUNT EXIST ]
    "$editable Plant"
    "$editable Storage Location"
    "$editable Material"
    "$editable Count"
    ^$editable Unit of Measure^
    [ COUNT ]
    Cumulative Count
    Inventory Document
    Inventory Document Line Number
    System Quantity
    Posted Quantity
    ===
    <i>Notes
    Only show PREV COUNT button if unposted counts exist
    ... for the current inventory document line
    Cumulative Count = Unposted counts gathered so far
    System Quantity = Current stock quantity in SAP
    Posted Quantity = Previously posted count (if applicable)
}
!endprocedure

!procedure _materialPreviouslyCounted()
{
    = Unposted Count Exists
    ---
    {
        [ MENU ]|[ CLEAR ]|[ POST ]
    }
    ...
    [ PREV COUNT EXIST ]
    "$editable Material"
    "$editable Count"
    ^$editable Unit of Measure^
    [ COUNT ]
    Cumulative Count
    Inventory Document
    Inventory Document Line Number
    System Quantity
    Posted Quantity
    ===
    <i>Notes 
}
!endprocedure

!procedure _displayCumulativeCount()
{
    = Accumulated Count Display
    ---
    {
        [ MENU ]|[ CLEAR ]|[ POST ]
    }
    ...
    [ RETURN ]
    Cumulative Count
    Inventory Document
    Inventory Document Line Number
    {S
        {#
            List of Unposted Counts for Current Material|*|*
            Count Quantity|UoM|Converted Qty
        }
    }
}
!endprocedure

!procedure _posted()
{
    = Post Sent to SAP
    ===
    <i>Notes
    Send lines with Cumulative Count Qty > 0
    Call COUNT or CHANGECOUNT as appropriate
}
!endprocedure

!procedure _postingResultDisplay()
{
    = Post Result Display
    ---
    {
        [ MENU ]|[ CLEAR ]|[ POST ]
    }
    ...
    [ RETURN ]
    {S
        {#
            List of Post Results for each Line Item|*|*
            Document Number|Line Number|Status Message
        }
    }
    ===
    <i>Notes 
}
!endprocedure

(*) --> [$button Menu Selection] SALT(initial)
initial --> [$userentry Material Entry] "Gathering Data" as Gathering<<ScreenGroup>>
Gathering --> [$button POST] SALT(posted)
Gathering --> [$button CLEAR\nAll unposted entries discarded] initial
posted -$sysevt-> SALT(postingResultDisplay)
postingResultDisplay --> [$button RETURN] initial

partition "Gathering Data" {
    Gathering -[dotted]-> SALT(materialValid)
    materialValid --> [$button PREV COUNT EXIST\n(If Selected Material has Unposted Count)\nDisplay Details of Previous Count(s)] SALT(displayCumulativeCount)
    displayCumulativeCount --> [$button RETURN] materialValid
    materialValid --> [$button COUNT\n(If Current Required Entries are Complete)\nSave Current Count] materialValid
}

@enduml